import type { Metadata } from 'next'
import './next.scss'
export const metadata: Metadata = {
  title: 'Next APP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="dark-scheme">
      {children}
      </body>
    </html>
  )
}
