import type { Metadata } from 'next'
import './themes.scss'
export const metadata: Metadata = {
  title: 'Next APP Sparrow',
  description: 'Generated by Sparrwozoo'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        NEXT Inner Layout
      {children}
      </body>
    </html>
  )
}
