// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LocaleLayout": {
    "title": "sparrow zoo"
  },
  "LocaleSwitcher": {
    "label": "Change language to \uD83C\uDDFA\uD83C\uDDF8 English",
    "locale": "{locale, select, zh {\uD83C\uDDE8\uD83C\uDDF3 中文} en {🇺🇸 English} other {Unknown}}"
  },
  "Header": {
    "index": "Home",
    "blog": "Blog",
    "im": "IM",
    "client-server": "Client Server",
    "shop": "Shop",
    "playground": "Write Blog",
    "theme-toggle": "Toggle Theme",
    "light-mode": "Light Mode",
    "dark-mode": "Dark Mode",
    "system-mode": "System Mode",
    "avatar-setting": "Avatar Setting",
    "logout": "Logout",
    "sign-in": "Sign In",
    "sign-up": "Sign Up"
  },
  "Passport": {
    "sign-in": {
      "sign-in": "Login",
      "username": "Username/Email",
      "user_password_error": "password error",
      "user_name_not_exist": "User name does not exist",
      "sign-in-title": "Login",
      "sign-in-title2": "please input your username and password",
      "sign-in-success": "Login Success !",
      "to-sign-up": "not register?",
      "sign-up": "Sign Up",
      "sign-in-with-wechat": "Sign in with WeChat",
      "remember-me": "Remember Me",
      "password": "Password",
      "captcha": "Captcha",
      "global_validate_code_error": "Captcha error, please try again input",
      "system_server_error": "System error, please try again later"
    },
    "find-password": {
      "forgot-password": "Forgot Password?",
      "input-email-to-find-password": "Please input your email to find password",
      "find-password": "Find Password",
      "send-find-password-email": "Send Email",
      "password-reset-email-sent": "Password reset email sent, please check your email",
      "close": "Close",
      "global_validate_code_error": "Captcha error, please try again input",
      "system_server_error": "System error, please try again later"
    },
    "PasswordTokenVerify": {
      "token-not-found": "Token not found",
      "new-password": "please input your new password",
      "password-format-error": "Password format error, please input again",
      "confirm-password-not-empty": "Please confirm your password",
      "password-not-match": "Password not match",
      "password-reset-success": "Password reset success, please login again",
      "password-reset-title": "Reset Password",
      "password-reset-description": "Minimum 8 characters with at least 1 letter, 1 number, and 1 special character ($, @, !, %, *, #, ?, &).",
      "new-password-title": "New Password",
      "confirm-password-title": "Confirm Password",
      "confirm": "Confirm"
    },
    "sign-up": {
      "sign-up": "Sign Up",
      "sign-up-success": "Register Success !",
      "sign-up-title": "Register",
      "email": "email",
      "username": "username",
      "password-confirm": "confirm password",
      "continue-with": "Or continue with",
      "to-sign-in": "registered? ",
      "sign-in": "Sign in ",
      "user_email_exist": "Email already exists",
      "user_name_exist": "user name already exists",
      "global_validate_code_error": "Captcha error, please try again input",
      "system_server_error": "System error, please try again later",
      "password": "Password",
      "captcha": "Captcha"
    }
  },
  "AvatarUploader": {
    "upload-success": "Upload Success !",
    "system_server_error": "System error, please try again later",
    "image_not_found": "Image not found,please upload image",
    "preview": "Preview",
    "settings": "Settings",
    "dragging-image-to-upload": "Drag image to upload",
    "click": "Click",
    "upload-image": "Upload Image",
    "width": "Width",
    "height": "Height",
    "scale": "Scale",
    "show-grid": "Show Grid",
    "border-radius": "Border Radius",
    "rotate-scale": "Rotate Scale",
    "background-color": "Background Color",
    "border-color": "Border Color",
    "opacity": "Opacity",
    "save": "Save",
    "or": "Or"
  }
};
export default messages;