import { Metadata, Viewport } from "next";
import * as React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};

/**
 * The root layout is defined at the top level of the app directory and applies to all routes.
 * This layout is required and must contain html and body tags,
 * allowing you to modify the initial HTML returned from the server.
 */
export default function RootLayout({
                                     children
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <h1>Welcome to Next.js!</h1>
      {children}
      这是layout组件的时间，会被持久化
      {new Date().toLocaleString()}
    </div>
  );
}
