const USER_INFO_KEY = "user_info";
const NODE_ENV = process.env.NODE_ENV;
const API_BASIC_URL = process.env.NEXT_PUBLIC_API;

const TOKEN_STORAGE = process.env.NEXT_PUBLIC_TOKEN_STORAGE;

const TOKEN_KEY = process.env.NEXT_PUBLIC_TOKEN_KEY as string;

const SESSION_STORAGE = "SESSION";

const NEXT_ASSET_PREFIX = process.env.NEXT_PUBLIC_ASSET_PREFIX;

export {
  NODE_ENV,
  API_BASIC_URL,
  TOKEN_KEY,
  TOKEN_STORAGE,
  SESSION_STORAGE,
  USER_INFO_KEY,
  NEXT_ASSET_PREFIX,
};
