"use client";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import { darkTheme } from "@/app/theme";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <ThemeProvider theme={darkTheme}>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
